version: '3.8'

services:
  main-app:
    image: main-app:latest
    build:
      context: ./main-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
    depends_on:
      - consumer
    networks:
      - app-network

  consumer:
    image: consumer-app:latest
    build:
      context: ./consumer
    ports:
      - "8081:8081"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
