spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: user
    password: user
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      platform: h2

jwt:
  secret: aWqjCUl12Dis6tsFc0zB4AF2bphXOSrU3OVBIZbUcw5ZuidX2wAzBLc5g7iiHTcI

logging:
  level:
    org:
      springframework:
        security: DEBUG
